-- GY DATA — Database Bootstrap SQL
-- Run once on a fresh environment to create all required tables and types.
-- Generated by inspecting lib/db/src/schema/* and every INSERT/SELECT in
-- artifacts/api-server/src/routes/* and lib/*.
-- Safe to re-run: all CREATE statements use IF NOT EXISTS / DO $$ BEGIN … END $$
-- guards that swallow duplicate-object errors.
--
-- Steps to provision a new environment:
--   1. Set DATABASE_URL in the deployment environment.
--   2. psql "$DATABASE_URL" -f db/bootstrap.sql
--   3. Set SESSION_SECRET in the deployment environment.
--   4. Start the API server (it seeds the super_admin account on first boot).

-- ── Enum types ────────────────────────────────────────────────────────────────

DO $$ BEGIN
  CREATE TYPE kyc_status AS ENUM ('unverified', 'pending', 'verified', 'rejected');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE account_status AS ENUM ('active', 'suspended', 'closed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE txn_type AS ENUM ('data', 'airtime', 'electricity', 'cable', 'betting', 'exam', 'wallet_fund');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE txn_status AS ENUM ('success', 'pending', 'failed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE notif_type AS ENUM ('transaction', 'promo', 'system', 'security');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE admin_role AS ENUM (
    'super_admin', 'admin', 'customer_care', 'finance', 'supervisor', 'technical_support'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE admin_account_status AS ENUM ('active', 'disabled');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ── users ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  id                UUID           NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name              TEXT           NOT NULL,
  first_name        TEXT           NOT NULL,
  last_name         TEXT           NOT NULL DEFAULT '',
  email             TEXT           NOT NULL,
  phone             TEXT           NOT NULL UNIQUE,
  username          TEXT           UNIQUE,
  username_changed_at TIMESTAMP,
  login_pin_hash    TEXT           NOT NULL,
  purchase_pin_hash TEXT,
  account_number    TEXT           NOT NULL UNIQUE,
  bank_name         TEXT           NOT NULL DEFAULT 'GY DATA Wallet',
  referral_code     TEXT           NOT NULL UNIQUE,
  kyc_status        kyc_status     NOT NULL DEFAULT 'unverified',
  status            account_status NOT NULL DEFAULT 'active',
  reset_otp_hash    TEXT,
  reset_otp_expiry  TIMESTAMP,
  created_at        TIMESTAMP      NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMP      NOT NULL DEFAULT NOW()
);
ALTER TABLE users ADD COLUMN IF NOT EXISTS username TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS username_changed_at TIMESTAMP;
DO $$ BEGIN
  CREATE UNIQUE INDEX IF NOT EXISTS users_username_key ON users (username) WHERE username IS NOT NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ── wallets ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS wallets (
  id          UUID          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id     UUID          NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  balance     NUMERIC(15,2) NOT NULL DEFAULT 0 CHECK (balance >= 0),
  created_at  TIMESTAMP     NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMP     NOT NULL DEFAULT NOW()
);

-- ── transactions ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS transactions (
  id                 UUID          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id            UUID          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type               txn_type      NOT NULL,
  service            TEXT          NOT NULL,
  provider           TEXT          NOT NULL,
  amount             NUMERIC(15,2) NOT NULL,
  cost_price         NUMERIC(15,2),
  status             txn_status    NOT NULL DEFAULT 'pending',
  reference          TEXT          UNIQUE,
  provider_reference TEXT,
  description        TEXT          NOT NULL DEFAULT '',
  payment_method     TEXT,
  metadata           JSONB,
  created_at         TIMESTAMP     NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMP     NOT NULL DEFAULT NOW()
);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS cost_price NUMERIC(15,2);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS provider_reference TEXT;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW();

-- ── notifications ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS notifications (
  id         UUID       NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id    UUID       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type       notif_type NOT NULL DEFAULT 'system',
  title      TEXT       NOT NULL,
  body       TEXT       NOT NULL DEFAULT '',
  read       BOOLEAN    NOT NULL DEFAULT FALSE,
  ref_id     TEXT,
  created_at TIMESTAMP  NOT NULL DEFAULT NOW()
);
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS ref_id text;

-- ── user_preferences ──────────────────────────────────────────────────────────
-- Stores per-user app settings (theme, hidden balance, etc.) as a JSONB blob.
CREATE TABLE IF NOT EXISTS user_preferences (
  id           UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id      UUID         NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  preferences  JSONB        NOT NULL DEFAULT '{}',
  updated_at   TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_user_preferences_user_id ON user_preferences (user_id);

-- ── admin accounts ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS admin_accounts (
  id                  UUID                 NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name                TEXT                 NOT NULL,
  email               TEXT                 NOT NULL UNIQUE,
  role                admin_role           NOT NULL DEFAULT 'admin',
  pin_hash            TEXT                 NOT NULL,
  status              admin_account_status NOT NULL DEFAULT 'active',
  created_by          UUID,
  finance_permissions JSONB                NOT NULL DEFAULT '[]'::jsonb,
  last_login_at       TIMESTAMP,
  created_at          TIMESTAMP            NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMP            NOT NULL DEFAULT NOW()
);
ALTER TABLE admin_accounts ADD COLUMN IF NOT EXISTS finance_permissions jsonb NOT NULL DEFAULT '[]'::jsonb;

-- ── admin audit logs ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id           UUID      NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  admin_id     UUID      NOT NULL REFERENCES admin_accounts(id) ON DELETE CASCADE,
  admin_email  TEXT      NOT NULL,
  action       TEXT      NOT NULL,
  target_type  TEXT,
  target_id    TEXT,
  target_label TEXT,
  details      JSONB,
  ip           TEXT,
  created_at   TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ── admin login history ───────────────────────────────────────────────────────
-- Written on every login attempt (success or failure) by routes/admin.ts.
CREATE TABLE IF NOT EXISTS admin_login_history (
  id          UUID      NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  admin_id    UUID      REFERENCES admin_accounts(id) ON DELETE SET NULL,
  admin_email TEXT,
  ip_address  TEXT,
  user_agent  TEXT,
  status      TEXT      NOT NULL DEFAULT 'success',   -- 'success' | 'failed'
  fail_reason TEXT,
  created_at  TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_admin_login_history_admin_id ON admin_login_history (admin_id);
CREATE INDEX IF NOT EXISTS idx_admin_login_history_created_at ON admin_login_history (created_at DESC);

-- ── admin sessions ────────────────────────────────────────────────────────────
-- Tracked for revocation by routes/admin-super.ts.
CREATE TABLE IF NOT EXISTS admin_sessions (
  id          UUID      NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  admin_id    UUID      REFERENCES admin_accounts(id) ON DELETE CASCADE,
  ip_address  TEXT,
  user_agent  TEXT,
  last_active TIMESTAMP NOT NULL DEFAULT NOW(),
  created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
  revoked_at  TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_admin_sessions_admin_id ON admin_sessions (admin_id);

-- ── session (connect-pg-simple) ───────────────────────────────────────────────
-- createTableIfMissing is unreliable in esbuild-bundled output (fs path breaks).
-- This table must exist before the API server starts.
CREATE TABLE IF NOT EXISTS session (
  sid    VARCHAR      NOT NULL COLLATE "default",
  sess   JSON         NOT NULL,
  expire TIMESTAMP(6) NOT NULL,
  CONSTRAINT session_pkey PRIMARY KEY (sid)
);
CREATE INDEX IF NOT EXISTS "IDX_session_expire" ON session (expire);

-- ── wallet_ledger ─────────────────────────────────────────────────────────────
-- Immutable, append-only audit trail for every wallet balance change.
-- Every credit, debit, reversal, and funding approval writes one row.
CREATE TABLE IF NOT EXISTS wallet_ledger (
  id                     UUID          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id                UUID          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  wallet_id              UUID          REFERENCES wallets(id) ON DELETE SET NULL,
  type                   TEXT          NOT NULL,   -- 'credit' | 'debit' | 'reversal' | 'wallet_fund' | 'adjustment'
  amount                 NUMERIC(15,2) NOT NULL,
  balance_before         NUMERIC(15,2) NOT NULL,
  balance_after          NUMERIC(15,2) NOT NULL,
  reference              TEXT          UNIQUE,
  related_transaction_id UUID          REFERENCES transactions(id) ON DELETE SET NULL,
  performed_by           UUID          REFERENCES admin_accounts(id) ON DELETE SET NULL,
  reason                 TEXT,
  created_at             TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_wallet_ledger_user_id ON wallet_ledger (user_id);
CREATE INDEX IF NOT EXISTS idx_wallet_ledger_created_at ON wallet_ledger (created_at DESC);

-- ── transaction_reversals ─────────────────────────────────────────────────────
-- Immutable record of every refund. Original transaction is never modified.
CREATE TABLE IF NOT EXISTS transaction_reversals (
  id                      UUID          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  original_transaction_id UUID          NOT NULL REFERENCES transactions(id) ON DELETE RESTRICT,
  user_id                 UUID          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount                  NUMERIC(15,2) NOT NULL,
  reason                  TEXT          NOT NULL,
  performed_by            UUID          REFERENCES admin_accounts(id) ON DELETE SET NULL,
  wallet_ledger_id        UUID          REFERENCES wallet_ledger(id) ON DELETE SET NULL,
  created_at              TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_transaction_reversals_user_id ON transaction_reversals (user_id);
CREATE INDEX IF NOT EXISTS idx_transaction_reversals_tx_id ON transaction_reversals (original_transaction_id);

-- ── funding_requests ──────────────────────────────────────────────────────────
-- Manual wallet top-up approvals submitted by users, reviewed by finance/admin.
CREATE TABLE IF NOT EXISTS funding_requests (
  id            UUID          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id       UUID          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount        NUMERIC(15,2) NOT NULL,
  status        TEXT          NOT NULL DEFAULT 'pending',   -- 'pending' | 'approved' | 'rejected'
  proof_url     TEXT,
  reviewed_by   UUID          REFERENCES admin_accounts(id) ON DELETE SET NULL,
  reviewed_at   TIMESTAMP,
  reject_reason TEXT,
  created_at    TIMESTAMP     NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_funding_requests_user_id ON funding_requests (user_id);
CREATE INDEX IF NOT EXISTS idx_funding_requests_status ON funding_requests (status);

-- ── financial_audit_logs ─────────────────────────────────────────────────────
-- Every finance-admin mutation (pricing change, wallet adjustment, refund).
-- Written by lib/financial-audit.ts financialAuditLog().
CREATE TABLE IF NOT EXISTS financial_audit_logs (
  id             UUID      NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  admin_id       UUID      NOT NULL REFERENCES admin_accounts(id) ON DELETE CASCADE,
  admin_name     TEXT,
  admin_email    TEXT,
  admin_role     TEXT      NOT NULL,
  action         TEXT      NOT NULL,
  entity_type    TEXT,
  entity_id      TEXT,
  customer_id    UUID      REFERENCES users(id) ON DELETE SET NULL,
  customer_name  TEXT,
  previous_value JSONB,
  new_value      JSONB,
  reason         TEXT,
  ip             TEXT,
  created_at     TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_financial_audit_logs_admin_id ON financial_audit_logs (admin_id);
CREATE INDEX IF NOT EXISTS idx_financial_audit_logs_created_at ON financial_audit_logs (created_at DESC);

-- ── pricing_rules ─────────────────────────────────────────────────────────────
-- Service pricing used by purchase.ts for price validation.
CREATE TABLE IF NOT EXISTS pricing_rules (
  id              UUID          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  service_type    TEXT          NOT NULL,
  provider        TEXT          NOT NULL,
  network         TEXT,
  plan_id         TEXT,
  plan_name       TEXT,
  cost_price      NUMERIC(15,2) NOT NULL DEFAULT 0,
  selling_price   NUMERIC(15,2) NOT NULL DEFAULT 0,
  markup_percent  NUMERIC(5,2)  NOT NULL DEFAULT 0,
  enabled         BOOLEAN       NOT NULL DEFAULT TRUE,
  updated_by      UUID          REFERENCES admin_accounts(id) ON DELETE SET NULL,
  updated_by_name TEXT,
  reason          TEXT,
  effective_date  DATE,
  created_at      TIMESTAMP     NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_pricing_rules_service_type ON pricing_rules (service_type);
CREATE INDEX IF NOT EXISTS idx_pricing_rules_enabled ON pricing_rules (enabled);

-- ── pricing_audit_logs ────────────────────────────────────────────────────────
-- Written by the pricingAuditLog() helper in admin-super.ts.
CREATE TABLE IF NOT EXISTS pricing_audit_logs (
  id                UUID          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  pricing_rule_id   UUID          REFERENCES pricing_rules(id) ON DELETE SET NULL,
  admin_id          UUID          NOT NULL REFERENCES admin_accounts(id) ON DELETE CASCADE,
  admin_name        TEXT,
  admin_email       TEXT,
  action            TEXT          NOT NULL,   -- 'create' | 'update' | 'bulk_update' | 'delete'
  service_type      TEXT,
  plan_name         TEXT,
  provider          TEXT,
  old_selling_price NUMERIC(15,2),
  new_selling_price NUMERIC(15,2),
  old_cost_price    NUMERIC(15,2),
  new_cost_price    NUMERIC(15,2),
  old_enabled       BOOLEAN,
  new_enabled       BOOLEAN,
  reason            TEXT,
  ip                TEXT,
  created_at        TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_pricing_audit_logs_admin_id ON pricing_audit_logs (admin_id);

-- ── system_settings ───────────────────────────────────────────────────────────
-- Key-value store for runtime flags: 2FA secrets, API enable/disable toggles.
CREATE TABLE IF NOT EXISTS system_settings (
  key        TEXT      NOT NULL PRIMARY KEY,
  value      TEXT      NOT NULL,
  updated_by UUID      REFERENCES admin_accounts(id) ON DELETE SET NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ── service_settings ──────────────────────────────────────────────────────────
-- Per-service enable/disable and markup overrides (data, airtime, electricity …).
CREATE TABLE IF NOT EXISTS service_settings (
  id          UUID      NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  service_key TEXT      NOT NULL UNIQUE,
  enabled     BOOLEAN   NOT NULL DEFAULT TRUE,
  markup      NUMERIC(5,2),
  notes       TEXT,
  updated_by  UUID      REFERENCES admin_accounts(id) ON DELETE SET NULL,
  updated_at  TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ── conversations ─────────────────────────────────────────────────────────────
-- One row per support session (WhatsApp thread or in-app chat).
CREATE TABLE IF NOT EXISTS conversations (
  id                UUID      NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  channel           TEXT      NOT NULL,                        -- 'whatsapp' | 'in_app'
  status            TEXT      NOT NULL DEFAULT 'open',         -- 'open' | 'assigned' | 'resolved' | 'closed'
  customer_id       UUID      REFERENCES users(id) ON DELETE SET NULL,
  customer_name     TEXT,
  customer_phone    TEXT,
  whatsapp_wa_id    TEXT      UNIQUE,                          -- Meta WhatsApp user ID
  subject           TEXT,
  last_message      TEXT,
  last_message_at   TIMESTAMP,
  unread_count      INTEGER   NOT NULL DEFAULT 0,
  assigned_staff_id UUID      REFERENCES admin_accounts(id) ON DELETE SET NULL,
  ai_handled        BOOLEAN   NOT NULL DEFAULT TRUE,
  human_claimed_at  TIMESTAMP,
  created_at        TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_conversations_status ON conversations (status);
CREATE INDEX IF NOT EXISTS idx_conversations_customer_id ON conversations (customer_id);
CREATE INDEX IF NOT EXISTS idx_conversations_last_message_at ON conversations (last_message_at DESC NULLS LAST);

-- ── messages ─────────────────────────────────────────────────────────────────
-- Individual chat messages within a conversation.
CREATE TABLE IF NOT EXISTS messages (
  id               UUID      NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  conversation_id  UUID      NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  content          TEXT      NOT NULL DEFAULT '',
  sender_type      TEXT      NOT NULL,                         -- 'user' | 'admin' | 'ai'
  sender_id        UUID,
  sender_name      TEXT,
  channel          TEXT,
  whatsapp_msg_id  TEXT      UNIQUE,                           -- Meta message ID for deduplication
  created_at       TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages (conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages (created_at ASC);

-- ── support_tickets ───────────────────────────────────────────────────────────
-- CC-role customer care tickets (distinct from chat conversations).
CREATE TABLE IF NOT EXISTS support_tickets (
  id                    UUID      NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  ticket_number         TEXT      NOT NULL UNIQUE,
  customer_id           UUID      REFERENCES users(id) ON DELETE SET NULL,
  customer_phone        TEXT,
  customer_name         TEXT,
  reason                TEXT      NOT NULL,
  status                TEXT      NOT NULL DEFAULT 'open',     -- 'open' | 'in_progress' | 'resolved' | 'closed'
  assigned_staff_id     UUID      REFERENCES admin_accounts(id) ON DELETE SET NULL,
  assigned_staff_name   TEXT,
  notes                 TEXT,
  otp_hash              TEXT,                                  -- bcrypt hash; NEVER returned to client
  otp_expiry            TIMESTAMP,
  otp_attempts          INTEGER   NOT NULL DEFAULT 0,
  otp_send_count        INTEGER   NOT NULL DEFAULT 0,
  otp_last_sent_at      TIMESTAMP,
  identity_verified     BOOLEAN   NOT NULL DEFAULT FALSE,
  pin_reset_approved    BOOLEAN   NOT NULL DEFAULT FALSE,
  pin_reset_approved_at TIMESTAMP,
  created_at            TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_support_tickets_customer_id ON support_tickets (customer_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_status ON support_tickets (status);

-- ── support_audit_logs ────────────────────────────────────────────────────────
-- Written by ccAudit() in admin-cc.ts on every CC staff action.
CREATE TABLE IF NOT EXISTS support_audit_logs (
  id                UUID      NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  ticket_id         UUID      REFERENCES support_tickets(id) ON DELETE SET NULL,
  customer_id       UUID      REFERENCES users(id) ON DELETE SET NULL,
  action            TEXT      NOT NULL,
  performed_by      UUID      REFERENCES admin_accounts(id) ON DELETE SET NULL,
  performed_by_name TEXT,
  details           JSONB     NOT NULL DEFAULT '{}'::jsonb,
  ip_address        TEXT,
  created_at        TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_support_audit_logs_ticket_id ON support_audit_logs (ticket_id);

-- ── user_status_history ───────────────────────────────────────────────────────
-- Immutable log of every account suspension / activation.
CREATE TABLE IF NOT EXISTS user_status_history (
  id              UUID      NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id         UUID      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  previous_status TEXT      NOT NULL,
  new_status      TEXT      NOT NULL,
  reason          TEXT,
  performed_by    UUID      REFERENCES admin_accounts(id) ON DELETE SET NULL,
  created_at      TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_user_status_history_user_id ON user_status_history (user_id);

-- ── staff_members ─────────────────────────────────────────────────────────────
-- HR records for admin staff (separate from admin_accounts login records).
CREATE TABLE IF NOT EXISTS staff_members (
  id                 UUID          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name               TEXT          NOT NULL,
  email              TEXT,
  phone              TEXT,
  role               TEXT          NOT NULL DEFAULT 'Staff',
  rank               TEXT          NOT NULL DEFAULT 'junior',
  salary             NUMERIC(15,2) NOT NULL DEFAULT 0,
  salary_payment_day INTEGER       NOT NULL DEFAULT 1,
  department         TEXT,
  status             TEXT          NOT NULL DEFAULT 'active',
  permissions        JSONB         NOT NULL DEFAULT '[]'::jsonb,
  notes              TEXT,
  admin_account_id   UUID          REFERENCES admin_accounts(id) ON DELETE SET NULL,
  created_at         TIMESTAMP     NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMP     NOT NULL DEFAULT NOW()
);

-- ── staff_attendance ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS staff_attendance (
  id         UUID      NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  staff_id   UUID      NOT NULL REFERENCES staff_members(id) ON DELETE CASCADE,
  date       DATE      NOT NULL,
  status     TEXT      NOT NULL DEFAULT 'present',  -- 'present' | 'absent' | 'late' | 'half_day'
  check_in   TEXT,
  check_out  TEXT,
  notes      TEXT,
  UNIQUE (staff_id, date)
);
CREATE INDEX IF NOT EXISTS idx_staff_attendance_staff_id ON staff_attendance (staff_id);

-- ── staff_activity_logs ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS staff_activity_logs (
  id         UUID      NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  staff_id   UUID      NOT NULL REFERENCES staff_members(id) ON DELETE CASCADE,
  action     TEXT      NOT NULL,
  metadata   JSONB     NOT NULL DEFAULT '{}'::jsonb,
  ip_address TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_staff_activity_logs_staff_id ON staff_activity_logs (staff_id);

-- ── Performance indexes on core tables ───────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_transactions_user_id       ON transactions (user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_status        ON transactions (status);
CREATE INDEX IF NOT EXISTS idx_transactions_created_at    ON transactions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_reference     ON transactions (reference);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id      ON notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_read         ON notifications (user_id, read);
CREATE INDEX IF NOT EXISTS idx_users_phone                ON users (phone);
CREATE INDEX IF NOT EXISTS idx_users_status               ON users (status);
CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_admin_id  ON admin_audit_logs (admin_id);
CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_created   ON admin_audit_logs (created_at DESC);

-- ═══════════════════════════════════════════════════════════════════════════════
-- CASHBACK SYSTEM
-- ═══════════════════════════════════════════════════════════════════════════════

-- Add cashback columns to pricing_rules (per-plan settings)
ALTER TABLE pricing_rules ADD COLUMN IF NOT EXISTS cashback_enabled BOOLEAN      NOT NULL DEFAULT FALSE;
ALTER TABLE pricing_rules ADD COLUMN IF NOT EXISTS cashback_type    TEXT         NOT NULL DEFAULT 'percentage';
ALTER TABLE pricing_rules ADD COLUMN IF NOT EXISTS cashback_value   NUMERIC(10,2) NOT NULL DEFAULT 0;

-- Global cashback on/off switch (exactly one row)
CREATE TABLE IF NOT EXISTS cashback_settings (
  id         UUID      NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  enabled    BOOLEAN   NOT NULL DEFAULT FALSE,
  updated_by UUID      REFERENCES admin_accounts(id) ON DELETE SET NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
INSERT INTO cashback_settings (enabled)
  SELECT false WHERE NOT EXISTS (SELECT 1 FROM cashback_settings);

-- Audit trail: one row per cashback credit event
CREATE TABLE IF NOT EXISTS cashback_transactions (
  id             UUID          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id        UUID          NOT NULL REFERENCES users(id)         ON DELETE CASCADE,
  source_txn_id  UUID          NOT NULL REFERENCES transactions(id)  ON DELETE CASCADE,
  wallet_txn_id  UUID                   REFERENCES transactions(id)  ON DELETE SET NULL,
  amount         NUMERIC(15,2) NOT NULL,
  cashback_type  TEXT          NOT NULL,   -- 'percentage' | 'fixed'
  cashback_value NUMERIC(10,2) NOT NULL,   -- the rule value that was applied
  network        TEXT,
  plan_id        TEXT,
  plan_name      TEXT,
  reference      TEXT          UNIQUE,
  created_at     TIMESTAMP     NOT NULL DEFAULT NOW(),
  CONSTRAINT cashback_once_per_txn UNIQUE (source_txn_id)
);
CREATE INDEX IF NOT EXISTS idx_cashback_txns_user_id    ON cashback_transactions (user_id);
CREATE INDEX IF NOT EXISTS idx_cashback_txns_created_at ON cashback_transactions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cashback_txns_network    ON cashback_transactions (network);
CREATE INDEX IF NOT EXISTS idx_cashback_txns_plan_id    ON cashback_transactions (plan_id);

-- ── Cashback wallet (separate from main wallet) ───────────────────────────────
-- Added: each user has a dedicated cashback balance; cashback credits go here,
-- not to the main wallet.  Users transfer to main wallet manually (or auto).
ALTER TABLE cashback_settings
  ADD COLUMN IF NOT EXISTS min_transfer_amount NUMERIC(15,2) NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS transfer_mode        TEXT         NOT NULL DEFAULT 'manual',
  ADD COLUMN IF NOT EXISTS eligible_services    JSONB        NOT NULL DEFAULT '["data"]'::jsonb;

CREATE TABLE IF NOT EXISTS cashback_wallets (
  id         UUID          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id    UUID          NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  balance    NUMERIC(15,2) NOT NULL DEFAULT 0 CHECK (balance >= 0),
  created_at TIMESTAMP     NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_cashback_wallets_user_id ON cashback_wallets (user_id);

-- Backfill cashback_wallets for existing users
INSERT INTO cashback_wallets (user_id, balance)
SELECT u.id, 0 FROM users u
WHERE NOT EXISTS (SELECT 1 FROM cashback_wallets cw WHERE cw.user_id = u.id);

CREATE TABLE IF NOT EXISTS cashback_transfers (
  id                 UUID          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id            UUID          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  cashback_wallet_id UUID          REFERENCES cashback_wallets(id) ON DELETE SET NULL,
  amount             NUMERIC(15,2) NOT NULL,
  balance_before     NUMERIC(15,2) NOT NULL,
  balance_after      NUMERIC(15,2) NOT NULL,
  main_txn_id        UUID          REFERENCES transactions(id) ON DELETE SET NULL,
  mode               TEXT          NOT NULL DEFAULT 'manual',
  created_at         TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_cashback_transfers_user_id    ON cashback_transfers (user_id);
CREATE INDEX IF NOT EXISTS idx_cashback_transfers_created_at ON cashback_transfers (created_at DESC);
