-- GY DATA — Database Bootstrap SQL
-- Run once on a fresh environment to create all required tables and types.
-- Generated by inspecting lib/db/src/schema/* and the live DB with \d / \dT+.
-- Safe to re-run: all CREATE statements use IF NOT EXISTS / DO $$ BEGIN … END $$
-- guards that swallow duplicate-object errors.
--
-- Steps to provision a new environment:
--   1. Set DATABASE_URL in Replit Secrets.
--   2. psql "$DATABASE_URL" -f db/bootstrap.sql
--   3. Set SESSION_SECRET in Replit Secrets.
--   4. Start the API server.

-- ── Enum types ────────────────────────────────────────────────────────────────
-- Exact names and values from lib/db/src/schema/*.ts

DO $$ BEGIN
  CREATE TYPE kyc_status AS ENUM ('unverified', 'pending', 'verified', 'rejected');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE account_status AS ENUM ('active', 'suspended', 'closed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  -- pgEnum name: txn_type (from txnTypeEnum in schema/transactions.ts)
  CREATE TYPE txn_type AS ENUM ('data', 'airtime', 'electricity', 'cable', 'betting', 'exam', 'wallet_fund');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  -- pgEnum name: txn_status (from txnStatusEnum in schema/transactions.ts)
  CREATE TYPE txn_status AS ENUM ('success', 'pending', 'failed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  -- pgEnum name: notif_type (from notifTypeEnum in schema/notifications.ts)
  -- Values: transaction | promo | system | security
  CREATE TYPE notif_type AS ENUM ('transaction', 'promo', 'system', 'security');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ── users ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  id                UUID           NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name              TEXT           NOT NULL,
  first_name        TEXT           NOT NULL,
  last_name         TEXT           NOT NULL DEFAULT '',
  email             TEXT           NOT NULL,
  phone             TEXT           NOT NULL UNIQUE,
  login_pin_hash    TEXT           NOT NULL,
  purchase_pin_hash TEXT,
  account_number    TEXT           NOT NULL UNIQUE,
  bank_name         TEXT           NOT NULL DEFAULT 'GY DATA Wallet',
  referral_code     TEXT           NOT NULL UNIQUE,
  kyc_status        kyc_status     NOT NULL DEFAULT 'unverified',
  status            account_status NOT NULL DEFAULT 'active',
  -- PIN-reset OTP challenge (bcrypt hash + expiry; cleared after single use)
  reset_otp_hash    TEXT,
  reset_otp_expiry  TIMESTAMP,
  created_at        TIMESTAMP      NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMP      NOT NULL DEFAULT NOW()
);

-- ── wallets ───────────────────────────────────────────────────────────────────
-- numeric(15,2) matches lib/db/src/schema/wallets.ts { precision: 15, scale: 2 }
CREATE TABLE IF NOT EXISTS wallets (
  id          UUID          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id     UUID          NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  balance     NUMERIC(15,2) NOT NULL DEFAULT 0,
  created_at  TIMESTAMP     NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMP     NOT NULL DEFAULT NOW()
);

-- ── transactions ──────────────────────────────────────────────────────────────
-- numeric(15,2) matches { precision: 15, scale: 2 }
-- metadata jsonb is part of the schema (nullable, used for vendor-specific data)
CREATE TABLE IF NOT EXISTS transactions (
  id             UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id        UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type           txn_type    NOT NULL,
  service        TEXT        NOT NULL,
  provider       TEXT        NOT NULL,
  amount         NUMERIC(15,2) NOT NULL,
  status         txn_status  NOT NULL DEFAULT 'pending',
  reference      TEXT        UNIQUE,        -- nullable; external vendor ref
  description    TEXT        NOT NULL DEFAULT '',
  payment_method TEXT,                      -- nullable
  metadata       JSONB,                     -- nullable; vendor-specific data
  created_at     TIMESTAMP   NOT NULL DEFAULT NOW()
);

-- ── notifications ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS notifications (
  id         UUID       NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id    UUID       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type       notif_type NOT NULL DEFAULT 'system',
  title      TEXT       NOT NULL,
  body       TEXT       NOT NULL DEFAULT '',
  read       BOOLEAN    NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP  NOT NULL DEFAULT NOW()
);

-- ── session (connect-pg-simple) ───────────────────────────────────────────────
-- createTableIfMissing is unreliable in esbuild-bundled output (fs path breaks).
-- This table must exist before the API server starts.
CREATE TABLE IF NOT EXISTS session (
  sid    VARCHAR      NOT NULL COLLATE "default" PRIMARY KEY DEFERRABLE INITIALLY IMMEDIATE,
  sess   JSON         NOT NULL,
  expire TIMESTAMP(6) NOT NULL
);
CREATE INDEX IF NOT EXISTS "IDX_session_expire" ON session (expire);
