import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.gydatahub.app',

  appName: 'GY DATA',

  webDir: 'dist',

  bundledWebRuntime: false,

  android: {
    backgroundColor: '#FFFFFF',
  },

  plugins: {
    SplashScreen: {
      /*
       * Native Android splash will use the exact
       * GY DATA splash resource generated by
       * create-android-branding.mjs.
       */
      launchAutoHide: true,

      launchShowDuration: 0,

      launchFadeOutDuration: 0,

      backgroundColor: '#FFFFFF',

      androidSplashResourceName:
        'gy_data_splash',

      /*
       * CENTER keeps the complete logo in the
       * middle instead of stretching/cropping it.
       */
      androidScaleType: 'CENTER',

      showSpinner: false,
    },
  },
};

export default config;
